name: examples

on:
  push:
    paths:
      - "examples/**"
  pull_request:
    paths:
      - "examples/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: examples/go.mod
      - run: go test ./...
        working-directory: examples
